name: seguidora_env
channels:
  - defaults
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.11
  - hydra-core>=1.3.2
  - lightning>=2.4.0
  - lightly>=1.5.13
  - matplotlib>=3.9.2
  - torch>=2.5.0
  - torchvision>=0.20.0
