defaults:
  - override hydra/job_logging: disabled

seed: 0
fast_dev_run: false
limit_train_batches: null
log_dir: ./logs
data_dir: ~/projects/ocl/data/PetFace/
use_wandb: false
resume_chkpt: null
backbone: resnet18
max_epochs: 10
batch_size_per_device: 512
num_workers: 16
skip_validation: false
input_size: 224
cj_prob: 0.8
cj_strength: 1.0
cj_bright: 0.8
cj_contrast: 0.8
cj_sat: 0.8
cj_hue: 0.2
min_scale: 0.08
random_gray_scale: 0.2
gaussian_blur: 0.5
accelerator: gpu
devices: 2
ckpt_path: null
